services:
  web:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      WATCHPACK_POLLING:  "true"
    command: sh -c "npm install && npm run dev"
