services:
  wedding_planning:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace 
    command: sleep infinity
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ../:/workspace
